### ISSUE TITLE
Move tutorials from this repo to https://grand-challenge.org/documentation/ ?

### ISSUE THREAD

**Issue by jmsmkn** [DIAGNijmegen/gcapi-examples#4]
We have a lot of places for documentation and tutorials. I don't think this stand-alone repo needs to exist alongside it. I think that the best place to move this to would be on grand challenge itself. What do you think @kiranvaidhya @KhrystynaFaryna ?

**Comment by kiranvaidhya** [comment]
Sure, I'm fine with moving the tutorials inside [grand-challenge.org/documentation/](https://grand-challenge.org/documentation/). I agree that this need not stay as a standalone repo. However, most of the documentation in this repo stays inside Jupyter Notebooks. So the migration may not be that straightforward. @KhrystynaFaryna @amickan what do you think?

**Comment by kiranvaidhya** [comment]
An alternative would be to migrate these to `https://github.com/comic/grand-challenge.org/tutorials`, for example.

**Comment by amickan** [comment]
I think https://grand-challenge.org/documentation/ is the best place for those tutorials and I don't think it should be a problem to turn the Jupyter Notebook style tutorials into markdown for the documentation. We have already done that for the algorithm tutorial.

**Comment by kiranvaidhya** [comment]
@KhrystynaFaryna can you do the following as part of your 10% tasks?

- [ ] Migrate cells from the Jupyter Notebook as Markdown text to the documentation page
- [ ] Verify that things still work on the documentation page
- [ ] When you're done with the above two, notify James to delete the repo

**Comment by KhrystynaFaryna** [comment]
@kiranvaidhya will do.

**Comment by KhrystynaFaryna** [comment]
All of the contents have been moved to documentation. @jmsmkn you can delete this repo now.

**Comment by jmsmkn** [comment]
Thanks! Will do.
